std_msgs/Header header

uint8 localization_algo_id
uint8 target_object_id

sensor_msgs/PointCloud2 point_cloud
sensor_msgs/Image image

string weight_path
---
bool success
string message

sensor_msgs/PointCloud2 point_cloud